spring:
   profiles:
       active:
	  - dev 

spring:
    profiles: dev
    application:
         name: cloud-test-dev

spring:
    profiles: default
    application:
         name: cloud-test-default