spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: config-test-dev
  #cloud:
   # config:
    #  uri: http://localhost:3301
     # label: master
      #profile: prod


---
spring:
  profiles: default
  application:
    name: config-test-default
  #cloud:
   ##  uri: http://localhost:3301
     # label: master
      #profile: dev