spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: config-test-dev
  cloud:
    config:
    #  uri: http://localhost:3301
      label: master
      #profile: prod

eureka:
  instance:
    #hostname: eurekaServer
    prefer-ip-address: true
    # 配置使用指定IP
    #ip-address: 192.168.31.253
    #ip-address: 172.22.144.3
  client:
    register-with-eureka: false #当前服务不注册到 eureka 之中
    fetch-registry: false  #不通过eureka 获取注册信息
    healthcheck:
      enable: true
    service-url:
      #defaultZone: ${registry.uri2}
      defaultZone: http://bidata:123@eurekaServer:7001/eureka

---
spring:
  profiles: default
  application:
    name: config-test-default
  cloud:
   ##  uri: http://localhost:3301
       label: master
      #profile: dev

eureka:
  instance:
    #hostname: eurekaServer
    prefer-ip-address: true
    # 配置使用指定IP
    #ip-address: 192.168.31.253
    #ip-address: 172.22.144.3
  client:
    register-with-eureka: false #当前服务不注册到 eureka 之中
    fetch-registry: false  #不通过eureka 获取注册信息
    healthcheck:
      enable: true
    service-url:
      #defaultZone: ${registry.uri2}
      defaultZone: http://bidata:123@eurekaServer:7001/eureka