spring:
  profiles:
    active: dev
---
server:
  port: 8001
  
spring:
  profiles: dev
  application:
    name: point-eureka
  cloud:
    config:
    #  uri: http://localhost:3301
      label: master
      #profile: prod

security:
  basic:
    enabled: true #启用安全认证
  user:
    name: bigdata
    password: 123456


eureka:
  instance:
    hostname: eurekaServer
    prefer-ip-address: true
    # 配置使用指定IP

  client:
    register-with-eureka: false #当前服务不注册到 eureka 之中
    fetch-registry: false  #不通过eureka 获取注册信息
    healthcheck:
      enable: true
    service-url:
      #defaultZone: ${registry.uri2}
      defaultZone: http://bidata:123456@eurekaServer:8001/eureka