spring:
  profiles:
    active: dev

---
server:
  port: 9001


spring:
  profiles: dev
  application:
    name: cloud-product
  cloud:
    config:
      #  uri: http://localhost:3301
      label: master
      #profile: prod
  datasource:
    url: jdbc:mysql://10.253.0.40:3306/TENANT?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: lyyGgnBe2F7dRH4c
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      minIdle: 5
      useGlobalDataSourceStat: true
      validationQuery: SELECT 1 FROM DUAL
      initialSize: 5
      maxWait: 60000
      filters: stat,wall,slf4j
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      testWhileIdle: true
      testOnBorrow: false
      minEvictableIdleTimeMillis: 300000
      timeBetweenEvictionRunsMillis: 60000
      testOnReturn: false
      maxActive: 20
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        loginUsername: ${spring.security.user.name}
        loginPassword: ${spring.security.user.password}
        resetEnable: true

security:
  basic:
    enabled: true #启用安全认证
  user:
    name: bigdata
    password: 123456

      
eureka:
  instance:
    #hostname: eurekaServer
    prefer-ip-address: true
    # 配置使用指定IP


  client:
    healthcheck:
      enable: true
    service-url:
      # defaultZone: ${registry.uri}
      #defaultZone: http://bigdata:123@eurekaServer:7001/eureka,http://bigdata:123@eurekaServer2:7002/eureka
      defaultZone:  http://bigdata:123456@eurekaServer:8001/eureka

 